# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Valuation_Expert.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 783)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_26.addWidget(self.label_46)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_26.addWidget(self.dateEdit)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_26.addWidget(self.toolButton)
        self.verticalLayout_41.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_27.addWidget(self.label_47)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_27.addWidget(self.dateEdit_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_27.addWidget(self.toolButton_3)
        self.verticalLayout_41.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25.addLayout(self.verticalLayout_41)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_42.addWidget(self.label_48)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.verticalLayout_42.addWidget(self.lineEdit_48)
        self.horizontalLayout_28.addLayout(self.verticalLayout_42)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_43.addWidget(self.label_49)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.verticalLayout_43.addWidget(self.lineEdit_49)
        self.horizontalLayout_28.addLayout(self.verticalLayout_43)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_44.addWidget(self.label_50)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.verticalLayout_44.addWidget(self.lineEdit_50)
        self.horizontalLayout_28.addLayout(self.verticalLayout_44)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_45.addWidget(self.label_51)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.verticalLayout_45.addWidget(self.lineEdit_51)
        self.horizontalLayout_28.addLayout(self.verticalLayout_45)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_46.addWidget(self.label_52)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.verticalLayout_46.addWidget(self.lineEdit_52)
        self.horizontalLayout_28.addLayout(self.verticalLayout_46)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_47.addWidget(self.label_53)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.verticalLayout_47.addWidget(self.lineEdit_53)
        self.horizontalLayout_28.addLayout(self.verticalLayout_47)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_28)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.verticalLayout_40.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem1)
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_48.addWidget(self.label_54)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.verticalLayout_48.addWidget(self.lineEdit_54)
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_48.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_48.addWidget(self.radioButton_6)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_48.addWidget(self.radioButton)
        self.horizontalLayout_31.addLayout(self.verticalLayout_48)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_49.addItem(spacerItem2)
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_49.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_49.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_49.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_49.addWidget(self.label_58)
        self.horizontalLayout_31.addLayout(self.verticalLayout_49)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_31.addLayout(self.verticalLayout)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_50.addWidget(self.label_59)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.verticalLayout_50.addWidget(self.lineEdit_55)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.verticalLayout_50.addWidget(self.lineEdit_56)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.verticalLayout_50.addWidget(self.lineEdit_57)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.verticalLayout_50.addWidget(self.lineEdit_58)
        self.horizontalLayout_31.addLayout(self.verticalLayout_50)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_51.addWidget(self.label_60)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.verticalLayout_51.addWidget(self.lineEdit_59)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.verticalLayout_51.addWidget(self.lineEdit_60)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.verticalLayout_51.addWidget(self.lineEdit_61)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.verticalLayout_51.addWidget(self.lineEdit_62)
        self.horizontalLayout_31.addLayout(self.verticalLayout_51)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem4)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_52.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_52.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_52.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_52.addWidget(self.pushButton_25)
        self.horizontalLayout_31.addLayout(self.verticalLayout_52)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem5)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_53.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_53.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_53.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_53.addWidget(self.pushButton_29)
        self.horizontalLayout_30.addLayout(self.verticalLayout_53)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_30)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_54.addWidget(self.label_61)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.verticalLayout_54.addWidget(self.lineEdit_63)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_54.addItem(spacerItem6)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_32.addWidget(self.label_62)
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_32.addWidget(self.comboBox_7)
        self.verticalLayout_54.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_29.addLayout(self.verticalLayout_54)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem7)
        self.verticalLayout_40.addLayout(self.horizontalLayout_29)
        self.verticalLayout_39.addLayout(self.verticalLayout_40)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_65)
        self.label_66 = QtWidgets.QLabel(self.groupBox)
        self.label_66.setObjectName("label_66")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_66)
        self.label_64 = QtWidgets.QLabel(self.groupBox)
        self.label_64.setObjectName("label_64")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.label_65 = QtWidgets.QLabel(self.groupBox)
        self.label_65.setObjectName("label_65")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.horizontalLayout.addWidget(self.lineEdit_64)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_33.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName("groupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_68 = QtWidgets.QLabel(self.groupBox1)
        self.label_68.setObjectName("label_68")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_68)
        self.label_69 = QtWidgets.QLabel(self.groupBox1)
        self.label_69.setObjectName("label_69")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_69)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_68)
        self.label_70 = QtWidgets.QLabel(self.groupBox1)
        self.label_70.setObjectName("label_70")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_70)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_69)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.horizontalLayout_2.addWidget(self.lineEdit_67)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox1)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_2.addWidget(self.toolButton_4)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_33.addWidget(self.groupBox1)
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setObjectName("groupBox2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_72 = QtWidgets.QLabel(self.groupBox2)
        self.label_72.setObjectName("label_72")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_72)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_70 = QtWidgets.QLineEdit(self.groupBox2)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.horizontalLayout_3.addWidget(self.lineEdit_70)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox2)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_3.addWidget(self.toolButton_5)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_73 = QtWidgets.QLabel(self.groupBox2)
        self.label_73.setObjectName("label_73")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_73)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.groupBox2)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_71)
        self.label_74 = QtWidgets.QLabel(self.groupBox2)
        self.label_74.setObjectName("label_74")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_74)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.groupBox2)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_72)
        self.horizontalLayout_33.addWidget(self.groupBox2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem8)
        self.verticalLayout_39.addLayout(self.horizontalLayout_33)
        self.verticalLayout_38.addLayout(self.verticalLayout_39)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(16)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        self.verticalLayout_38.addWidget(self.tableWidget_2)
        self.verticalLayout_58.addLayout(self.verticalLayout_38)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem9)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_17.addWidget(self.label_22)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_17.addWidget(self.label_24)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_17.addWidget(self.label_23)
        self.horizontalLayout_15.addLayout(self.verticalLayout_17)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_11.addWidget(self.label_18)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_10.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_10.addWidget(self.lineEdit_18)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_10.addWidget(self.lineEdit_16)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_13.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_13.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_13.addWidget(self.lineEdit_21)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem13 = QtWidgets.QSpacerItem(13, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem13)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_16.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_16.addWidget(self.lineEdit_26)
        spacerItem14 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem15)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_15.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_15.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_15.addWidget(self.lineEdit_24)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.horizontalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem16 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_18.addItem(spacerItem16)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_18.addWidget(self.pushButton)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_18.addWidget(self.lineEdit_27)
        self.horizontalLayout_15.addLayout(self.verticalLayout_18)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        spacerItem17 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_59.addItem(spacerItem17)
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_59.addWidget(self.label_75)
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_59.addWidget(self.label_76)
        self.horizontalLayout_44.addLayout(self.verticalLayout_59)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        spacerItem18 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_60.addItem(spacerItem18)
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_60.addWidget(self.label_77)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.lineEdit_73 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.horizontalLayout_45.addWidget(self.lineEdit_73)
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_45.addWidget(self.label_78)
        spacerItem19 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem19)
        self.verticalLayout_60.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.lineEdit_74 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.horizontalLayout_46.addWidget(self.lineEdit_74)
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_46.addWidget(self.label_79)
        spacerItem20 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem20)
        self.verticalLayout_60.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_44.addLayout(self.verticalLayout_60)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_44)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem21)
        self.verticalLayout_37.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_16.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_16.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_16.addWidget(self.pushButton_5)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.verticalLayout_37.addLayout(self.horizontalLayout_16)
        self.verticalLayout_58.addLayout(self.verticalLayout_37)
        self.horizontalLayout_43.addLayout(self.verticalLayout_58)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionFirm = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons8-organization-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirm.setIcon(icon)
        self.actionFirm.setObjectName("actionFirm")
        self.actionValuer = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons8-user-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionValuer.setIcon(icon1)
        self.actionValuer.setObjectName("actionValuer")
        self.actionGroups = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons8-list-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGroups.setIcon(icon2)
        self.actionGroups.setObjectName("actionGroups")
        self.actionItems = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons8-ring-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItems.setIcon(icon3)
        self.actionItems.setObjectName("actionItems")
        self.actionMarket_Rates = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons8-us-dollar-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMarket_Rates.setIcon(icon4)
        self.actionMarket_Rates.setObjectName("actionMarket_Rates")
        self.actionValuation = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons8-contract-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionValuation.setIcon(icon5)
        self.actionValuation.setObjectName("actionValuation")
        self.actionChange_Password = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons8-password-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChange_Password.setIcon(icon6)
        self.actionChange_Password.setObjectName("actionChange_Password")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons8-about-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons8-exit-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionFirm)
        self.toolBar.addAction(self.actionValuer)
        self.toolBar.addAction(self.actionGroups)
        self.toolBar.addAction(self.actionItems)
        self.toolBar.addAction(self.actionMarket_Rates)
        self.toolBar.addAction(self.actionValuation)
        self.toolBar.addAction(self.actionChange_Password)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_46.setText(_translate("MainWindow", "Rate Date:"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_47.setText(_translate("MainWindow", "Valuation Date:"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.label_48.setText(_translate("MainWindow", "Gold(10 g)"))
        self.label_49.setText(_translate("MainWindow", "Silver(1 kg)"))
        self.label_50.setText(_translate("MainWindow", "Platinum"))
        self.label_51.setText(_translate("MainWindow", "Diamond"))
        self.label_52.setText(_translate("MainWindow", "Soverign"))
        self.label_53.setText(_translate("MainWindow", "Coin"))
        self.label_54.setText(_translate("MainWindow", "Valuation Amount"))
        self.radioButton_5.setText(_translate("MainWindow", "Amount"))
        self.radioButton_6.setText(_translate("MainWindow", "Weight"))
        self.radioButton.setText(_translate("MainWindow", "Percentage"))
        self.label_55.setText(_translate("MainWindow", "Gold"))
        self.label_56.setText(_translate("MainWindow", "Silver"))
        self.label_57.setText(_translate("MainWindow", "Platinum"))
        self.label_58.setText(_translate("MainWindow", "White Metal"))
        self.checkBox_4.setText(_translate("MainWindow", "Diamond"))
        self.checkBox_3.setText(_translate("MainWindow", "Diamond"))
        self.checkBox_2.setText(_translate("MainWindow", "Diamond"))
        self.checkBox.setText(_translate("MainWindow", "Diamond"))
        self.label_59.setText(_translate("MainWindow", "%"))
        self.label_60.setText(_translate("MainWindow", "Qty."))
        self.pushButton_22.setText(_translate("MainWindow", "Valuate Gold"))
        self.pushButton_23.setText(_translate("MainWindow", "Valuate Silver"))
        self.pushButton_24.setText(_translate("MainWindow", "Valuate Platinum"))
        self.pushButton_25.setText(_translate("MainWindow", "Valuate White Metal"))
        self.pushButton_26.setText(_translate("MainWindow", "Clear"))
        self.pushButton_27.setText(_translate("MainWindow", "Clear"))
        self.pushButton_28.setText(_translate("MainWindow", "Clear"))
        self.pushButton_29.setText(_translate("MainWindow", "Clear"))
        self.label_61.setText(_translate("MainWindow", "Calculation Status"))
        self.label_62.setText(_translate("MainWindow", "Exclude Group"))
        self.groupBox.setTitle(_translate("MainWindow", "Valuers"))
        self.label_66.setText(_translate("MainWindow", "Purpose"))
        self.label_64.setText(_translate("MainWindow", "Name"))
        self.label_65.setText(_translate("MainWindow", "R.No."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.groupBox1.setTitle(_translate("MainWindow", "Customer"))
        self.label_68.setText(_translate("MainWindow", "Name"))
        self.label_69.setText(_translate("MainWindow", "Address 1"))
        self.label_70.setText(_translate("MainWindow", "Address 2"))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.groupBox2.setTitle(_translate("MainWindow", "Firm"))
        self.label_72.setText(_translate("MainWindow", "Name"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.label_73.setText(_translate("MainWindow", "Address"))
        self.label_74.setText(_translate("MainWindow", "Under O/S with"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rate"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Purity"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Qty."))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gross Wt."))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Metal Wt."))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Value(Metal)"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Stone(Description)"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Wt (Stone)"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Rate(Stone)"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Value(Stone)"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Total Value"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Metal"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Item Ratewise"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Stone Weightwise"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Is_Soverign"))
        self.label_22.setText(_translate("MainWindow", "Gold"))
        self.label_24.setText(_translate("MainWindow", "Silver"))
        self.label_23.setText(_translate("MainWindow", "Diamond"))
        self.label_18.setText(_translate("MainWindow", "Total Qty."))
        self.label_19.setText(_translate("MainWindow", "Gross Wt."))
        self.label_21.setText(_translate("MainWindow", "Metal Wt."))
        self.label_20.setText(_translate("MainWindow", "Value"))
        self.pushButton.setText(_translate("MainWindow", "Check Purity Wise Total"))
        self.label_75.setText(_translate("MainWindow", "Gold"))
        self.label_76.setText(_translate("MainWindow", "Silver/Pt."))
        self.label_77.setText(_translate("MainWindow", "Min Purity"))
        self.label_78.setText(_translate("MainWindow", "Ct"))
        self.label_79.setText(_translate("MainWindow", "%"))
        self.pushButton_2.setText(_translate("MainWindow", "New"))
        self.pushButton_3.setText(_translate("MainWindow", "Valuation Bill"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.pushButton_5.setText(_translate("MainWindow", "Close"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionFirm.setText(_translate("MainWindow", "Firm"))
        self.actionFirm.setToolTip(_translate("MainWindow", "Firm"))
        self.actionFirm.setShortcut(_translate("MainWindow", "Alt+F"))
        self.actionValuer.setText(_translate("MainWindow", "Valuer"))
        self.actionValuer.setToolTip(_translate("MainWindow", "Valuer"))
        self.actionValuer.setShortcut(_translate("MainWindow", "Alt+V"))
        self.actionGroups.setText(_translate("MainWindow", "Groups"))
        self.actionGroups.setToolTip(_translate("MainWindow", "Groups"))
        self.actionGroups.setShortcut(_translate("MainWindow", "Alt+G"))
        self.actionItems.setText(_translate("MainWindow", "Items"))
        self.actionItems.setToolTip(_translate("MainWindow", "Items"))
        self.actionItems.setShortcut(_translate("MainWindow", "Alt+I"))
        self.actionMarket_Rates.setText(_translate("MainWindow", "Market Rates"))
        self.actionMarket_Rates.setToolTip(_translate("MainWindow", "Market Rates"))
        self.actionMarket_Rates.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionValuation.setText(_translate("MainWindow", "Valuation"))
        self.actionValuation.setToolTip(_translate("MainWindow", "Valuation"))
        self.actionValuation.setShortcut(_translate("MainWindow", "Alt+A"))
        self.actionChange_Password.setText(_translate("MainWindow", "Change Password"))
        self.actionChange_Password.setToolTip(_translate("MainWindow", "Change Password"))
        self.actionChange_Password.setShortcut(_translate("MainWindow", "Alt+P"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setToolTip(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Alt+B"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))


import toolbar_rc
